'use client'
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "react-query"; 1

const mont = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Beauty Pro 2.0",
//   description: "Generated by create next app",
// };

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mont.className}>
        {/* <PrimeReactProvider> */}
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        {/* </PrimeReactProvider> */}
      </body>
    </html>
  );
}
